// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·andKernel(SB), NOSPLIT, $0-80
	MOVV dst_base+0(FP), R4
	MOVV dst_len+8(FP), R5
	MOVV a_base+24(FP), R6
	MOVV a_len+32(FP), R7
	MOVV b_base+48(FP), R8
	MOVV b_len+56(FP), R9
	BLT R7, R5, useY1
	MOVV R5, R5
	JMP doneMin1
useY1:
	MOVV R7, R5
doneMin1:
	BLT R9, R5, useY2
	MOVV R5, R5
	JMP doneMin2
useY2:
	MOVV R9, R5
doneMin2:
	SRLV $1, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	SLLV $3, R11, R12
	ADDV R6, R12, R13
	ADDV R8, R12, R14
	ADDV R4, R12, R15
	VMOVQ (R13), V0
	VMOVQ (R14), V1
	VANDV V1, V0, V0
	VMOVQ V0, (R15)
	ADDV $2, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R11, done+72(FP)
	RET

TEXT ·orKernel(SB), NOSPLIT, $0-80
	MOVV dst_base+0(FP), R4
	MOVV dst_len+8(FP), R5
	MOVV a_base+24(FP), R6
	MOVV a_len+32(FP), R7
	MOVV b_base+48(FP), R8
	MOVV b_len+56(FP), R9
	BLT R7, R5, useY3
	MOVV R5, R5
	JMP doneMin3
useY3:
	MOVV R7, R5
doneMin3:
	BLT R9, R5, useY4
	MOVV R5, R5
	JMP doneMin4
useY4:
	MOVV R9, R5
doneMin4:
	SRLV $1, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	SLLV $3, R11, R12
	ADDV R6, R12, R13
	ADDV R8, R12, R14
	ADDV R4, R12, R15
	VMOVQ (R13), V0
	VMOVQ (R14), V1
	VORV V1, V0, V0
	VMOVQ V0, (R15)
	ADDV $2, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R11, done+72(FP)
	RET

TEXT ·xorKernel(SB), NOSPLIT, $0-80
	MOVV dst_base+0(FP), R4
	MOVV dst_len+8(FP), R5
	MOVV a_base+24(FP), R6
	MOVV a_len+32(FP), R7
	MOVV b_base+48(FP), R8
	MOVV b_len+56(FP), R9
	BLT R7, R5, useY5
	MOVV R5, R5
	JMP doneMin5
useY5:
	MOVV R7, R5
doneMin5:
	BLT R9, R5, useY6
	MOVV R5, R5
	JMP doneMin6
useY6:
	MOVV R9, R5
doneMin6:
	SRLV $1, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	SLLV $3, R11, R12
	ADDV R6, R12, R13
	ADDV R8, R12, R14
	ADDV R4, R12, R15
	VMOVQ (R13), V0
	VMOVQ (R14), V1
	VXORV V1, V0, V0
	VMOVQ V0, (R15)
	ADDV $2, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R11, done+72(FP)
	RET

TEXT ·andNotKernel(SB), NOSPLIT, $0-80
	MOVV dst_base+0(FP), R4
	MOVV dst_len+8(FP), R5
	MOVV a_base+24(FP), R6
	MOVV a_len+32(FP), R7
	MOVV b_base+48(FP), R8
	MOVV b_len+56(FP), R9
	BLT R7, R5, useY7
	MOVV R5, R5
	JMP doneMin7
useY7:
	MOVV R7, R5
doneMin7:
	BLT R9, R5, useY8
	MOVV R5, R5
	JMP doneMin8
useY8:
	MOVV R9, R5
doneMin8:
	SRLV $1, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	SLLV $3, R11, R12
	ADDV R6, R12, R13
	ADDV R8, R12, R14
	ADDV R4, R12, R15
	VMOVQ (R13), V0
	VMOVQ (R14), V1
	VANDNV V0, V1, V0
	VMOVQ V0, (R15)
	ADDV $2, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R11, done+72(FP)
	RET

TEXT ·countKernel(SB), NOSPLIT, $0-40
	MOVV a_base+0(FP), R4
	MOVV a_len+8(FP), R5
	MOVV $0, R6
	SRLV $1, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	SLLV $3, R11, R12
	ADDV R4, R12, R13
	VMOVQ (R13), V0
	VPCNTV V0, V0
	VMOVQ V0.V[0], R14
	VMOVQ V0.V[1], R15
	ADDV R14, R6, R6
	ADDV R15, R6, R6
	ADDV $2, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R6, sum+24(FP)
	MOVV R11, done+32(FP)
	RET

TEXT ·intersectionKernel(SB), NOSPLIT, $0-64
	MOVV a_base+0(FP), R4
	MOVV a_len+8(FP), R5
	MOVV b_base+24(FP), R8
	MOVV b_len+32(FP), R9
	BLT R9, R5, useY9
	MOVV R5, R5
	JMP doneMin9
useY9:
	MOVV R9, R5
doneMin9:
	MOVV $0, R6
	SRLV $1, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	SLLV $3, R11, R12
	ADDV R4, R12, R13
	ADDV R8, R12, R14
	VMOVQ (R13), V0
	VMOVQ (R14), V1
	VANDV V1, V0, V0
	VPCNTV V0, V0
	VMOVQ V0.V[0], R15
	VMOVQ V0.V[1], R16
	ADDV R15, R6, R6
	ADDV R16, R6, R6
	ADDV $2, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R6, sum+48(FP)
	MOVV R11, done+56(FP)
	RET

TEXT ·unionKernel(SB), NOSPLIT, $0-64
	MOVV a_base+0(FP), R4
	MOVV a_len+8(FP), R5
	MOVV b_base+24(FP), R8
	MOVV b_len+32(FP), R9
	BLT R9, R5, useY10
	MOVV R5, R5
	JMP doneMin10
useY10:
	MOVV R9, R5
doneMin10:
	MOVV $0, R6
	SRLV $1, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	SLLV $3, R11, R12
	ADDV R4, R12, R13
	ADDV R8, R12, R14
	VMOVQ (R13), V0
	VMOVQ (R14), V1
	VORV V1, V0, V0
	VPCNTV V0, V0
	VMOVQ V0.V[0], R15
	VMOVQ V0.V[1], R16
	ADDV R15, R6, R6
	ADDV R16, R6, R6
	ADDV $2, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R6, sum+48(FP)
	MOVV R11, done+56(FP)
	RET

TEXT ·differenceKernel(SB), NOSPLIT, $0-64
	MOVV a_base+0(FP), R4
	MOVV a_len+8(FP), R5
	MOVV b_base+24(FP), R8
	MOVV b_len+32(FP), R9
	BLT R9, R5, useY11
	MOVV R5, R5
	JMP doneMin11
useY11:
	MOVV R9, R5
doneMin11:
	MOVV $0, R6
	SRLV $1, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	SLLV $3, R11, R12
	ADDV R4, R12, R13
	ADDV R8, R12, R14
	VMOVQ (R13), V0
	VMOVQ (R14), V1
	VANDNV V0, V1, V0
	VPCNTV V0, V0
	VMOVQ V0.V[0], R15
	VMOVQ V0.V[1], R16
	ADDV R15, R6, R6
	ADDV R16, R6, R6
	ADDV $2, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R6, sum+48(FP)
	MOVV R11, done+56(FP)
	RET

