//go:build loong64

package bitset

// LSX kernels over whole 2-uint64 (16-byte) blocks, returning the words consumed
// (a multiple of 2). LSX is treated as the loong64 baseline (as in the sibling
// go-simd/popcount). Generated by go-asmgen (bitset_loong64_gen.go), in
// bitset_loong64.s.
func andKernel(dst, a, b []uint64) (done int)
func orKernel(dst, a, b []uint64) (done int)
func xorKernel(dst, a, b []uint64) (done int)
func andNotKernel(dst, a, b []uint64) (done int)

func countKernel(a []uint64) (sum, done int)
func intersectionKernel(a, b []uint64) (sum, done int)
func unionKernel(a, b []uint64) (sum, done int)
func differenceKernel(a, b []uint64) (sum, done int)

const blockWords = 2

func and(dst, a, b []uint64) {
	done := 0
	if min3(len(dst), len(a), len(b)) >= blockWords {
		done = andKernel(dst, a, b)
	}
	andScalarRef(dst[done:], a[done:], b[done:])
}

func or(dst, a, b []uint64) {
	done := 0
	if min3(len(dst), len(a), len(b)) >= blockWords {
		done = orKernel(dst, a, b)
	}
	orScalarRef(dst[done:], a[done:], b[done:])
}

func xor(dst, a, b []uint64) {
	done := 0
	if min3(len(dst), len(a), len(b)) >= blockWords {
		done = xorKernel(dst, a, b)
	}
	xorScalarRef(dst[done:], a[done:], b[done:])
}

func andNot(dst, a, b []uint64) {
	done := 0
	if min3(len(dst), len(a), len(b)) >= blockWords {
		done = andNotKernel(dst, a, b)
	}
	andNotScalarRef(dst[done:], a[done:], b[done:])
}

func count(a []uint64) int {
	if len(a) >= blockWords {
		sum, done := countKernel(a)
		return sum + countScalarRef(a[done:])
	}
	return countScalarRef(a)
}

func intersectionCount(a, b []uint64) int {
	if min2(len(a), len(b)) >= blockWords {
		sum, done := intersectionKernel(a, b)
		return sum + intersectionCountScalarRef(a[done:], b[done:])
	}
	return intersectionCountScalarRef(a, b)
}

func unionCount(a, b []uint64) int {
	if min2(len(a), len(b)) >= blockWords {
		sum, done := unionKernel(a, b)
		return sum + unionCountScalarRef(a[done:], b[done:])
	}
	return unionCountScalarRef(a, b)
}

func differenceCount(a, b []uint64) int {
	if min2(len(a), len(b)) >= blockWords {
		sum, done := differenceKernel(a, b)
		return sum + differenceCountScalarRef(a[done:], b[done:])
	}
	return differenceCountScalarRef(a, b)
}
