//go:build ppc64le

package bitset

import "golang.org/x/sys/cpu"

// VSX kernels over whole 2-uint64 (16-byte) blocks, returning the words consumed
// (a multiple of 2). The generated kernels emit ISA-3.0 (POWER9) instructions
// (e.g. MFVSRLD), which raise SIGILL on POWER8, so they run only when hasVSX
// reports POWER9+; on POWER8 the pure-Go scalar reference does all the work.
// Generated by go-asmgen (bitset_ppc64le_gen.go), in bitset_ppc64le.s.
func andKernel(dst, a, b []uint64) (done int)
func orKernel(dst, a, b []uint64) (done int)
func xorKernel(dst, a, b []uint64) (done int)
func andNotKernel(dst, a, b []uint64) (done int)

func countKernel(a []uint64) (sum, done int)
func intersectionKernel(a, b []uint64) (sum, done int)
func unionKernel(a, b []uint64) (sum, done int)
func differenceKernel(a, b []uint64) (sum, done int)

const blockWords = 2

// hasVSX gates the generated kernels. They use ISA-3.0 (POWER9) VSX
// instructions (e.g. MFVSRLD) that are illegal on POWER8, so the kernel is
// invoked only on POWER9+; otherwise the scalar reference handles everything.
// It is a var (not a const) so the dispatch test can also drive the fallback.
var hasVSX = cpu.PPC64.IsPOWER9

func and(dst, a, b []uint64) {
	done := 0
	if hasVSX && min3(len(dst), len(a), len(b)) >= blockWords {
		done = andKernel(dst, a, b)
	}
	andScalarRef(dst[done:], a[done:], b[done:])
}

func or(dst, a, b []uint64) {
	done := 0
	if hasVSX && min3(len(dst), len(a), len(b)) >= blockWords {
		done = orKernel(dst, a, b)
	}
	orScalarRef(dst[done:], a[done:], b[done:])
}

func xor(dst, a, b []uint64) {
	done := 0
	if hasVSX && min3(len(dst), len(a), len(b)) >= blockWords {
		done = xorKernel(dst, a, b)
	}
	xorScalarRef(dst[done:], a[done:], b[done:])
}

func andNot(dst, a, b []uint64) {
	done := 0
	if hasVSX && min3(len(dst), len(a), len(b)) >= blockWords {
		done = andNotKernel(dst, a, b)
	}
	andNotScalarRef(dst[done:], a[done:], b[done:])
}

func count(a []uint64) int {
	if hasVSX && len(a) >= blockWords {
		sum, done := countKernel(a)
		return sum + countScalarRef(a[done:])
	}
	return countScalarRef(a)
}

func intersectionCount(a, b []uint64) int {
	if hasVSX && min2(len(a), len(b)) >= blockWords {
		sum, done := intersectionKernel(a, b)
		return sum + intersectionCountScalarRef(a[done:], b[done:])
	}
	return intersectionCountScalarRef(a, b)
}

func unionCount(a, b []uint64) int {
	if hasVSX && min2(len(a), len(b)) >= blockWords {
		sum, done := unionKernel(a, b)
		return sum + unionCountScalarRef(a[done:], b[done:])
	}
	return unionCountScalarRef(a, b)
}

func differenceCount(a, b []uint64) int {
	if hasVSX && min2(len(a), len(b)) >= blockWords {
		sum, done := differenceKernel(a, b)
		return sum + differenceCountScalarRef(a[done:], b[done:])
	}
	return differenceCountScalarRef(a, b)
}
