// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·andKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R1
	MOVD dst_len+8(FP), R2
	MOVD a_base+24(FP), R3
	MOVD a_len+32(FP), R4
	MOVD b_base+48(FP), R5
	MOVD b_len+56(FP), R6
	CMPBLT R4, R2, useY1
	MOVD R2, R2
	BR doneMin1
useY1:
	MOVD R4, R2
doneMin1:
	CMPBLT R6, R2, useY2
	MOVD R2, R2
	BR doneMin2
useY2:
	MOVD R6, R2
doneMin2:
	SRD $1, R2, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	SLD $3, R8, R9
	ADD R3, R9, R10
	ADD R5, R9, R11
	ADD R1, R9, R12
	VL (R10), V0
	VL (R11), V1
	VN V1, V0, V2
	VST V2, (R12)
	ADD $2, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R8, done+72(FP)
	RET

TEXT ·orKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R1
	MOVD dst_len+8(FP), R2
	MOVD a_base+24(FP), R3
	MOVD a_len+32(FP), R4
	MOVD b_base+48(FP), R5
	MOVD b_len+56(FP), R6
	CMPBLT R4, R2, useY3
	MOVD R2, R2
	BR doneMin3
useY3:
	MOVD R4, R2
doneMin3:
	CMPBLT R6, R2, useY4
	MOVD R2, R2
	BR doneMin4
useY4:
	MOVD R6, R2
doneMin4:
	SRD $1, R2, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	SLD $3, R8, R9
	ADD R3, R9, R10
	ADD R5, R9, R11
	ADD R1, R9, R12
	VL (R10), V0
	VL (R11), V1
	VO V1, V0, V2
	VST V2, (R12)
	ADD $2, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R8, done+72(FP)
	RET

TEXT ·xorKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R1
	MOVD dst_len+8(FP), R2
	MOVD a_base+24(FP), R3
	MOVD a_len+32(FP), R4
	MOVD b_base+48(FP), R5
	MOVD b_len+56(FP), R6
	CMPBLT R4, R2, useY5
	MOVD R2, R2
	BR doneMin5
useY5:
	MOVD R4, R2
doneMin5:
	CMPBLT R6, R2, useY6
	MOVD R2, R2
	BR doneMin6
useY6:
	MOVD R6, R2
doneMin6:
	SRD $1, R2, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	SLD $3, R8, R9
	ADD R3, R9, R10
	ADD R5, R9, R11
	ADD R1, R9, R12
	VL (R10), V0
	VL (R11), V1
	VX V1, V0, V2
	VST V2, (R12)
	ADD $2, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R8, done+72(FP)
	RET

TEXT ·andNotKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R1
	MOVD dst_len+8(FP), R2
	MOVD a_base+24(FP), R3
	MOVD a_len+32(FP), R4
	MOVD b_base+48(FP), R5
	MOVD b_len+56(FP), R6
	CMPBLT R4, R2, useY7
	MOVD R2, R2
	BR doneMin7
useY7:
	MOVD R4, R2
doneMin7:
	CMPBLT R6, R2, useY8
	MOVD R2, R2
	BR doneMin8
useY8:
	MOVD R6, R2
doneMin8:
	SRD $1, R2, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	SLD $3, R8, R9
	ADD R3, R9, R10
	ADD R5, R9, R11
	ADD R1, R9, R12
	VL (R10), V0
	VL (R11), V1
	VNC V0, V1, V2
	VST V2, (R12)
	ADD $2, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R8, done+72(FP)
	RET

TEXT ·countKernel(SB), NOSPLIT, $0-40
	MOVD a_base+0(FP), R3
	MOVD a_len+8(FP), R4
	MOVD $0, R5
	VZERO V5
	SRD $1, R4, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	SLD $3, R8, R9
	ADD R3, R9, R10
	VL (R10), V0
	VPOPCT V0, V1
	VSUMB V1, V5, V1
	VSUMQF V1, V5, V1
	VLGVG $1, V1, R11
	ADD R11, R5, R5
	ADD $2, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R5, sum+24(FP)
	MOVD R8, done+32(FP)
	RET

TEXT ·intersectionKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R3
	MOVD a_len+8(FP), R4
	MOVD b_base+24(FP), R5
	MOVD b_len+32(FP), R6
	CMPBLT R6, R4, useY9
	MOVD R4, R4
	BR doneMin9
useY9:
	MOVD R6, R4
doneMin9:
	MOVD $0, R2
	VZERO V5
	SRD $1, R4, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	SLD $3, R8, R9
	ADD R3, R9, R10
	ADD R5, R9, R11
	VL (R10), V0
	VL (R11), V1
	VN V1, V0, V2
	VPOPCT V2, V2
	VSUMB V2, V5, V2
	VSUMQF V2, V5, V2
	VLGVG $1, V2, R12
	ADD R12, R2, R2
	ADD $2, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R2, sum+48(FP)
	MOVD R8, done+56(FP)
	RET

TEXT ·unionKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R3
	MOVD a_len+8(FP), R4
	MOVD b_base+24(FP), R5
	MOVD b_len+32(FP), R6
	CMPBLT R6, R4, useY10
	MOVD R4, R4
	BR doneMin10
useY10:
	MOVD R6, R4
doneMin10:
	MOVD $0, R2
	VZERO V5
	SRD $1, R4, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	SLD $3, R8, R9
	ADD R3, R9, R10
	ADD R5, R9, R11
	VL (R10), V0
	VL (R11), V1
	VO V1, V0, V2
	VPOPCT V2, V2
	VSUMB V2, V5, V2
	VSUMQF V2, V5, V2
	VLGVG $1, V2, R12
	ADD R12, R2, R2
	ADD $2, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R2, sum+48(FP)
	MOVD R8, done+56(FP)
	RET

TEXT ·differenceKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R3
	MOVD a_len+8(FP), R4
	MOVD b_base+24(FP), R5
	MOVD b_len+32(FP), R6
	CMPBLT R6, R4, useY11
	MOVD R4, R4
	BR doneMin11
useY11:
	MOVD R6, R4
doneMin11:
	MOVD $0, R2
	VZERO V5
	SRD $1, R4, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	SLD $3, R8, R9
	ADD R3, R9, R10
	ADD R5, R9, R11
	VL (R10), V0
	VL (R11), V1
	VNC V0, V1, V2
	VPOPCT V2, V2
	VSUMB V2, V5, V2
	VSUMQF V2, V5, V2
	VLGVG $1, V2, R12
	ADD R12, R2, R2
	ADD $2, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R2, sum+48(FP)
	MOVD R8, done+56(FP)
	RET

