//go:build amd64

package bitset

import "golang.org/x/sys/cpu"

// Logical-op kernels: dst[i] = a[i] OP b[i] over whole 4-uint64 blocks via AVX2,
// returning the number of words consumed (a multiple of 4). The kernel reads the
// three slice lengths and operates over n = min of them. Generated by go-asmgen
// (bitset_amd64_gen.go), in bitset_amd64.s.
func andKernel(dst, a, b []uint64) (done int)
func orKernel(dst, a, b []uint64) (done int)
func xorKernel(dst, a, b []uint64) (done int)
func andNotKernel(dst, a, b []uint64) (done int)

// Count kernels via hardware POPCNTQ over whole 4-word blocks, returning the
// partial popcount and the words consumed (a multiple of 4). The pairwise
// kernels fuse the boolean op (in a GPR) with the popcount.
func countKernel(a []uint64) (sum, done int)
func intersectionKernel(a, b []uint64) (sum, done int)
func unionKernel(a, b []uint64) (sum, done int)
func differenceKernel(a, b []uint64) (sum, done int)

var (
	hasAVX2   = cpu.X86.HasAVX2
	hasPOPCNT = cpu.X86.HasPOPCNT
)

// Per-kernel minimum: one 4-word (32-byte) block. Below it the scalar loop wins
// (kernel call setup does not amortise).
const blockWords = 4

func and(dst, a, b []uint64) {
	n := min3(len(dst), len(a), len(b))
	done := 0
	if hasAVX2 && n >= blockWords {
		done = andKernel(dst, a, b)
	}
	andScalarRef(dst[done:], a[done:], b[done:])
}

func or(dst, a, b []uint64) {
	n := min3(len(dst), len(a), len(b))
	done := 0
	if hasAVX2 && n >= blockWords {
		done = orKernel(dst, a, b)
	}
	orScalarRef(dst[done:], a[done:], b[done:])
}

func xor(dst, a, b []uint64) {
	n := min3(len(dst), len(a), len(b))
	done := 0
	if hasAVX2 && n >= blockWords {
		done = xorKernel(dst, a, b)
	}
	xorScalarRef(dst[done:], a[done:], b[done:])
}

func andNot(dst, a, b []uint64) {
	n := min3(len(dst), len(a), len(b))
	done := 0
	if hasAVX2 && n >= blockWords {
		done = andNotKernel(dst, a, b)
	}
	andNotScalarRef(dst[done:], a[done:], b[done:])
}

func count(a []uint64) int {
	if hasPOPCNT && len(a) >= blockWords {
		sum, done := countKernel(a)
		return sum + countScalarRef(a[done:])
	}
	return countScalarRef(a)
}

func intersectionCount(a, b []uint64) int {
	n := min2(len(a), len(b))
	if hasPOPCNT && n >= blockWords {
		sum, done := intersectionKernel(a, b)
		return sum + intersectionCountScalarRef(a[done:], b[done:])
	}
	return intersectionCountScalarRef(a, b)
}

func unionCount(a, b []uint64) int {
	n := min2(len(a), len(b))
	if hasPOPCNT && n >= blockWords {
		sum, done := unionKernel(a, b)
		return sum + unionCountScalarRef(a[done:], b[done:])
	}
	return unionCountScalarRef(a, b)
}

func differenceCount(a, b []uint64) int {
	n := min2(len(a), len(b))
	if hasPOPCNT && n >= blockWords {
		sum, done := differenceKernel(a, b)
		return sum + differenceCountScalarRef(a[done:], b[done:])
	}
	return differenceCountScalarRef(a, b)
}
