// Package bitset provides SIMD-accelerated bulk bit-set operations over a bit
// set stored as a slice of 64-bit words ([]uint64, little-endian within each
// word: word w bit b is set bit w*64+b). It is pure Go (CGO_ENABLED=0, stable
// Go, no GOEXPERIMENT): the hot loops are SIMD kernels generated by go-asmgen.
//
// Two families of operation:
//
//   - Element-wise logical ops over the word stream — And, Or, AndNot, Xor —
//     each writing dst[i] = a[i] OP b[i]. They are in-place capable: dst may
//     alias a and/or b. The SIMD kernels are vector VPAND/VPOR/VPANDN/VPXOR
//     (amd64 AVX2), AND/ORR/BIC/EOR (arm64 NEON), VAND/VOR/VANDC/VXOR (ppc64le
//     VSX), VN/VO/VNC/VX (s390x vector facility) and the LSX VAND.V family
//     (loong64); riscv64 uses the portable scalar word loop.
//
//   - Population counts — Count (total set bits), IntersectionCount (popcount
//     of a&b), UnionCount (a|b), DifferenceCount (a&^b). These reuse the
//     go-simd/popcount kernels (amd64 POPCNTQ, arm64 NEON VCNT, ppc64le VSX
//     VPOPCNTD, s390x VPOPCT, loong64 LSX VPCNTV; riscv64 scalar) fused, for
//     the pairwise variants, with the corresponding logical op so the words are
//     never materialised.
//
// The honest framing: the logical ops and the counts are memory-bandwidth-bound
// for large, out-of-cache sets — a scalar math/bits loop already moves a word
// per cycle, so SIMD ties scalar there. The SIMD win is real for in-cache /
// medium sets, where the problem is compute-bound. See the README for measured,
// size-dependent throughput.
//
// CHECK-EXISTING: github.com/bits-and-blooms/bitset is the de-facto Go bit set
// (a rich BitSet type with Set/Test/Clear/iteration); its bulk ops are scalar
// math/bits loops over its backing []uint64. github.com/RoaringBitmap/roaring
// is a different, compressed structure (run/array/bitmap containers) — not a
// dense []uint64. This package is intentionally minimal: it operates directly
// on a caller-owned []uint64 and only accelerates the bulk word kernels, so it
// composes with either (bits-and-blooms exposes its words; roaring is a
// different model). It is the dense-[]uint64 SIMD complement, not a replacement.
package bitset

import "math/bits"

// And sets dst[i] = a[i] & b[i] for i in [0, n) where n = min(len(dst), len(a),
// len(b)). dst may alias a and/or b (in-place capable). Words of dst beyond n
// are left unchanged.
func And(dst, a, b []uint64) { and(dst, a, b) }

// Or sets dst[i] = a[i] | b[i] for i in [0, min(len(dst),len(a),len(b))). dst
// may alias a and/or b.
func Or(dst, a, b []uint64) { or(dst, a, b) }

// AndNot sets dst[i] = a[i] &^ b[i] (a AND NOT b) for i in [0, min(...)). dst
// may alias a and/or b.
func AndNot(dst, a, b []uint64) { andNot(dst, a, b) }

// Xor sets dst[i] = a[i] ^ b[i] for i in [0, min(...)). dst may alias a and/or
// b.
func Xor(dst, a, b []uint64) { xor(dst, a, b) }

// Count returns the total number of set bits across all words of a (its
// population count / Hamming weight).
func Count(a []uint64) int { return count(a) }

// IntersectionCount returns the number of set bits in a & b — the size of the
// intersection — without allocating: popcount(a[i]&b[i]) summed over i in
// [0, min(len(a),len(b))).
func IntersectionCount(a, b []uint64) int { return intersectionCount(a, b) }

// UnionCount returns the number of set bits in a | b — the size of the union —
// without allocating. Note this is the popcount of the elementwise OR over the
// shared length; words of the longer slice past min(len(a),len(b)) are not
// counted (callers wanting the full union should size both slices equally).
func UnionCount(a, b []uint64) int { return unionCount(a, b) }

// DifferenceCount returns the number of set bits in a &^ b (a AND NOT b) — the
// size of the set difference — without allocating, over i in [0, min(...)).
func DifferenceCount(a, b []uint64) int { return differenceCount(a, b) }

// min3 returns the common length the three-slice ops operate over.
func min3(a, b, c int) int {
	if b < a {
		a = b
	}
	if c < a {
		a = c
	}
	return a
}

// min2 returns the common length the two-slice ops operate over.
func min2(a, b int) int {
	if b < a {
		return b
	}
	return a
}

// Scalar references. These are the portable implementations (used on
// architectures without a SIMD kernel, including riscv64) and the independent
// baseline the SIMD kernels are checked against. Each is a tight word loop.

func andScalarRef(dst, a, b []uint64) {
	n := min3(len(dst), len(a), len(b))
	for i := 0; i < n; i++ {
		dst[i] = a[i] & b[i]
	}
}

func orScalarRef(dst, a, b []uint64) {
	n := min3(len(dst), len(a), len(b))
	for i := 0; i < n; i++ {
		dst[i] = a[i] | b[i]
	}
}

func andNotScalarRef(dst, a, b []uint64) {
	n := min3(len(dst), len(a), len(b))
	for i := 0; i < n; i++ {
		dst[i] = a[i] &^ b[i]
	}
}

func xorScalarRef(dst, a, b []uint64) {
	n := min3(len(dst), len(a), len(b))
	for i := 0; i < n; i++ {
		dst[i] = a[i] ^ b[i]
	}
}

func countScalarRef(a []uint64) int {
	total := 0
	for _, w := range a {
		total += bits.OnesCount64(w)
	}
	return total
}

func intersectionCountScalarRef(a, b []uint64) int {
	n := min2(len(a), len(b))
	total := 0
	for i := 0; i < n; i++ {
		total += bits.OnesCount64(a[i] & b[i])
	}
	return total
}

func unionCountScalarRef(a, b []uint64) int {
	n := min2(len(a), len(b))
	total := 0
	for i := 0; i < n; i++ {
		total += bits.OnesCount64(a[i] | b[i])
	}
	return total
}

func differenceCountScalarRef(a, b []uint64) int {
	n := min2(len(a), len(b))
	total := 0
	for i := 0; i < n; i++ {
		total += bits.OnesCount64(a[i] &^ b[i])
	}
	return total
}
