// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·andKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R3
	MOVD dst_len+8(FP), R4
	MOVD a_base+24(FP), R5
	MOVD a_len+32(FP), R6
	MOVD b_base+48(FP), R7
	MOVD b_len+56(FP), R8
	CMP R6, R4
	BLT useY1
	MOVD R4, R4
	BR doneMin1
useY1:
	MOVD R6, R4
doneMin1:
	CMP R8, R4
	BLT useY2
	MOVD R4, R4
	BR doneMin2
useY2:
	MOVD R8, R4
doneMin2:
	SRD $1, R4, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	SLD $3, R10, R11
	ADD R5, R11, R12
	ADD R7, R11, R14
	ADD R3, R11, R15
	LXVD2X (R12)(R0), VS32
	LXVD2X (R14)(R0), VS33
	VAND V0, V1, V2
	STXVD2X VS34, (R15)(R0)
	ADD $2, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R10, done+72(FP)
	RET

TEXT ·orKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R3
	MOVD dst_len+8(FP), R4
	MOVD a_base+24(FP), R5
	MOVD a_len+32(FP), R6
	MOVD b_base+48(FP), R7
	MOVD b_len+56(FP), R8
	CMP R6, R4
	BLT useY3
	MOVD R4, R4
	BR doneMin3
useY3:
	MOVD R6, R4
doneMin3:
	CMP R8, R4
	BLT useY4
	MOVD R4, R4
	BR doneMin4
useY4:
	MOVD R8, R4
doneMin4:
	SRD $1, R4, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	SLD $3, R10, R11
	ADD R5, R11, R12
	ADD R7, R11, R14
	ADD R3, R11, R15
	LXVD2X (R12)(R0), VS32
	LXVD2X (R14)(R0), VS33
	VOR V0, V1, V2
	STXVD2X VS34, (R15)(R0)
	ADD $2, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R10, done+72(FP)
	RET

TEXT ·xorKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R3
	MOVD dst_len+8(FP), R4
	MOVD a_base+24(FP), R5
	MOVD a_len+32(FP), R6
	MOVD b_base+48(FP), R7
	MOVD b_len+56(FP), R8
	CMP R6, R4
	BLT useY5
	MOVD R4, R4
	BR doneMin5
useY5:
	MOVD R6, R4
doneMin5:
	CMP R8, R4
	BLT useY6
	MOVD R4, R4
	BR doneMin6
useY6:
	MOVD R8, R4
doneMin6:
	SRD $1, R4, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	SLD $3, R10, R11
	ADD R5, R11, R12
	ADD R7, R11, R14
	ADD R3, R11, R15
	LXVD2X (R12)(R0), VS32
	LXVD2X (R14)(R0), VS33
	VXOR V0, V1, V2
	STXVD2X VS34, (R15)(R0)
	ADD $2, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R10, done+72(FP)
	RET

TEXT ·andNotKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R3
	MOVD dst_len+8(FP), R4
	MOVD a_base+24(FP), R5
	MOVD a_len+32(FP), R6
	MOVD b_base+48(FP), R7
	MOVD b_len+56(FP), R8
	CMP R6, R4
	BLT useY7
	MOVD R4, R4
	BR doneMin7
useY7:
	MOVD R6, R4
doneMin7:
	CMP R8, R4
	BLT useY8
	MOVD R4, R4
	BR doneMin8
useY8:
	MOVD R8, R4
doneMin8:
	SRD $1, R4, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	SLD $3, R10, R11
	ADD R5, R11, R12
	ADD R7, R11, R14
	ADD R3, R11, R15
	LXVD2X (R12)(R0), VS32
	LXVD2X (R14)(R0), VS33
	VANDC V0, V1, V2
	STXVD2X VS34, (R15)(R0)
	ADD $2, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R10, done+72(FP)
	RET

TEXT ·countKernel(SB), NOSPLIT, $0-40
	MOVD a_base+0(FP), R5
	MOVD a_len+8(FP), R6
	MOVD $0, R7
	SRD $1, R6, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	SLD $3, R10, R11
	ADD R5, R11, R12
	LXVD2X (R12)(R0), VS32
	VPOPCNTD V0, V0
	MFVSRD VS32, R13
	MFVSRLD VS32, R14
	ADD R13, R7, R7
	ADD R14, R7, R7
	ADD $2, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R7, sum+24(FP)
	MOVD R10, done+32(FP)
	RET

TEXT ·intersectionKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R5
	MOVD a_len+8(FP), R6
	MOVD b_base+24(FP), R7
	MOVD b_len+32(FP), R8
	CMP R8, R6
	BLT useY9
	MOVD R6, R6
	BR doneMin9
useY9:
	MOVD R8, R6
doneMin9:
	MOVD $0, R4
	SRD $1, R6, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	SLD $3, R10, R11
	ADD R5, R11, R12
	ADD R7, R11, R14
	LXVD2X (R12)(R0), VS32
	LXVD2X (R14)(R0), VS33
	VAND V0, V1, V2
	VPOPCNTD V2, V2
	MFVSRD VS34, R15
	MFVSRLD VS34, R16
	ADD R15, R4, R4
	ADD R16, R4, R4
	ADD $2, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R4, sum+48(FP)
	MOVD R10, done+56(FP)
	RET

TEXT ·unionKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R5
	MOVD a_len+8(FP), R6
	MOVD b_base+24(FP), R7
	MOVD b_len+32(FP), R8
	CMP R8, R6
	BLT useY10
	MOVD R6, R6
	BR doneMin10
useY10:
	MOVD R8, R6
doneMin10:
	MOVD $0, R4
	SRD $1, R6, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	SLD $3, R10, R11
	ADD R5, R11, R12
	ADD R7, R11, R14
	LXVD2X (R12)(R0), VS32
	LXVD2X (R14)(R0), VS33
	VOR V0, V1, V2
	VPOPCNTD V2, V2
	MFVSRD VS34, R15
	MFVSRLD VS34, R16
	ADD R15, R4, R4
	ADD R16, R4, R4
	ADD $2, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R4, sum+48(FP)
	MOVD R10, done+56(FP)
	RET

TEXT ·differenceKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R5
	MOVD a_len+8(FP), R6
	MOVD b_base+24(FP), R7
	MOVD b_len+32(FP), R8
	CMP R8, R6
	BLT useY11
	MOVD R6, R6
	BR doneMin11
useY11:
	MOVD R8, R6
doneMin11:
	MOVD $0, R4
	SRD $1, R6, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	SLD $3, R10, R11
	ADD R5, R11, R12
	ADD R7, R11, R14
	LXVD2X (R12)(R0), VS32
	LXVD2X (R14)(R0), VS33
	VANDC V0, V1, V2
	VPOPCNTD V2, V2
	MFVSRD VS34, R15
	MFVSRLD VS34, R16
	ADD R15, R4, R4
	ADD R16, R4, R4
	ADD $2, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R4, sum+48(FP)
	MOVD R10, done+56(FP)
	RET

