// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·andKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD dst_len+8(FP), R1
	MOVD a_base+24(FP), R2
	MOVD a_len+32(FP), R3
	MOVD b_base+48(FP), R4
	MOVD b_len+56(FP), R5
	CMP R3, R1
	CSEL LT, R1, R3, R1
	CMP R5, R1
	CSEL LT, R1, R5, R1
	LSR $1, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	LSL $3, R7, R8
	ADD R2, R8, R9
	ADD R4, R8, R10
	ADD R0, R8, R11
	VLD1 (R9), [V0.B16]
	VLD1 (R10), [V1.B16]
	VAND V1.B16, V0.B16, V0.B16
	VST1 [V0.B16], (R11)
	ADD $2, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R7, done+72(FP)
	RET

TEXT ·orKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD dst_len+8(FP), R1
	MOVD a_base+24(FP), R2
	MOVD a_len+32(FP), R3
	MOVD b_base+48(FP), R4
	MOVD b_len+56(FP), R5
	CMP R3, R1
	CSEL LT, R1, R3, R1
	CMP R5, R1
	CSEL LT, R1, R5, R1
	LSR $1, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	LSL $3, R7, R8
	ADD R2, R8, R9
	ADD R4, R8, R10
	ADD R0, R8, R11
	VLD1 (R9), [V0.B16]
	VLD1 (R10), [V1.B16]
	VORR V1.B16, V0.B16, V0.B16
	VST1 [V0.B16], (R11)
	ADD $2, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R7, done+72(FP)
	RET

TEXT ·xorKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD dst_len+8(FP), R1
	MOVD a_base+24(FP), R2
	MOVD a_len+32(FP), R3
	MOVD b_base+48(FP), R4
	MOVD b_len+56(FP), R5
	CMP R3, R1
	CSEL LT, R1, R3, R1
	CMP R5, R1
	CSEL LT, R1, R5, R1
	LSR $1, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	LSL $3, R7, R8
	ADD R2, R8, R9
	ADD R4, R8, R10
	ADD R0, R8, R11
	VLD1 (R9), [V0.B16]
	VLD1 (R10), [V1.B16]
	VEOR V1.B16, V0.B16, V0.B16
	VST1 [V0.B16], (R11)
	ADD $2, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R7, done+72(FP)
	RET

TEXT ·andNotKernel(SB), NOSPLIT, $0-80
	MOVD dst_base+0(FP), R0
	MOVD dst_len+8(FP), R1
	MOVD a_base+24(FP), R2
	MOVD a_len+32(FP), R3
	MOVD b_base+48(FP), R4
	MOVD b_len+56(FP), R5
	CMP R3, R1
	CSEL LT, R1, R3, R1
	CMP R5, R1
	CSEL LT, R1, R5, R1
	LSR $1, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	LSL $3, R7, R8
	ADD R2, R8, R9
	ADD R4, R8, R10
	ADD R0, R8, R11
	VLD1 (R9), [V0.B16]
	VLD1 (R10), [V1.B16]
	VAND V1.B16, V0.B16, V2.B16
	VEOR V2.B16, V0.B16, V0.B16
	VST1 [V0.B16], (R11)
	ADD $2, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R7, done+72(FP)
	RET

TEXT ·countKernel(SB), NOSPLIT, $0-40
	MOVD a_base+0(FP), R0
	MOVD a_len+8(FP), R1
	MOVD $0, R2
	LSR $1, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	LSL $3, R7, R8
	ADD R0, R8, R9
	VLD1 (R9), [V0.B16]
	VCNT V0.B16, V0.B16
	VUADDLV V0.B16, V0
	VMOV V0.D[0], R10
	ADD R10, R2, R2
	ADD $2, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R2, sum+24(FP)
	MOVD R7, done+32(FP)
	RET

TEXT ·intersectionKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R0
	MOVD a_len+8(FP), R1
	MOVD b_base+24(FP), R2
	MOVD b_len+32(FP), R3
	CMP R3, R1
	CSEL LT, R1, R3, R1
	MOVD $0, R4
	LSR $1, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	LSL $3, R7, R8
	ADD R0, R8, R9
	ADD R2, R8, R10
	VLD1 (R9), [V0.B16]
	VLD1 (R10), [V1.B16]
	VAND V1.B16, V0.B16, V0.B16
	VCNT V0.B16, V0.B16
	VUADDLV V0.B16, V0
	VMOV V0.D[0], R11
	ADD R11, R4, R4
	ADD $2, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R4, sum+48(FP)
	MOVD R7, done+56(FP)
	RET

TEXT ·unionKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R0
	MOVD a_len+8(FP), R1
	MOVD b_base+24(FP), R2
	MOVD b_len+32(FP), R3
	CMP R3, R1
	CSEL LT, R1, R3, R1
	MOVD $0, R4
	LSR $1, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	LSL $3, R7, R8
	ADD R0, R8, R9
	ADD R2, R8, R10
	VLD1 (R9), [V0.B16]
	VLD1 (R10), [V1.B16]
	VORR V1.B16, V0.B16, V0.B16
	VCNT V0.B16, V0.B16
	VUADDLV V0.B16, V0
	VMOV V0.D[0], R11
	ADD R11, R4, R4
	ADD $2, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R4, sum+48(FP)
	MOVD R7, done+56(FP)
	RET

TEXT ·differenceKernel(SB), NOSPLIT, $0-64
	MOVD a_base+0(FP), R0
	MOVD a_len+8(FP), R1
	MOVD b_base+24(FP), R2
	MOVD b_len+32(FP), R3
	CMP R3, R1
	CSEL LT, R1, R3, R1
	MOVD $0, R4
	LSR $1, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	LSL $3, R7, R8
	ADD R0, R8, R9
	ADD R2, R8, R10
	VLD1 (R9), [V0.B16]
	VLD1 (R10), [V1.B16]
	VAND V1.B16, V0.B16, V2.B16
	VEOR V2.B16, V0.B16, V0.B16
	VCNT V0.B16, V0.B16
	VUADDLV V0.B16, V0
	VMOV V0.D[0], R11
	ADD R11, R4, R4
	ADD $2, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R4, sum+48(FP)
	MOVD R7, done+56(FP)
	RET

